name: "Package" 
description: "Package the browser into a nice little package"
runs:
  using: "composite"
  steps:
    - name: Package
      shell: bash
      run: |
        python3 ./.github/workflows/actions/dependencies/${{ inputs.target }}.py
