name: "Install dependencies" 
description: "Install the required dependencies for the build"
inputs:
  target:
    description: 'Build target'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python3 ./.github/workflows/actions/dependencies/${{ inputs.target }}.py
