name: "Install dependencies" 
description: "Install the required dependencies for the build"
inputs:
  target:
    description: 'Build target'
    required: true
env:
  DEP_CMD: PYTHONPATH=.github/actions python3 ./.github/actions/dependencies/${{ inputs.target }}.py
runs:
  using: "composite"
  steps:
    - name: Install Sentry SDK
      shell: bash
      run: sudo pip install --upgrade sentry_sdk

    - name: Install apt dependencies
      shell: bash
      run: ${{ env.DEP_CMD }} apt

    - name: Install Rust
      shell: bash
      run: ${{ env.DEP_CMD }} rust

    - name: Install pip dependencies
      shell: bash
      run: ${{ env.DEP_CMD }} pip

    - name: Install cargo dependencies
      shell: bash
      run: ${{ env.DEP_CMD }} cargo