name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git User
        run: |
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git config --global user.name "dothq-robot"

      - name: Install dependencies
        run: |
          npm i typescript

      - name: Download workspace
        run: |
          CI_SKIP_INIT=true ./melon download
          cd src
          git init
          echo Init
          git checkout --orphan base
          echo Checkout
          git add -f .
          echo Add
          git commit -am "Firefox"
          echo Commit
          git checkout -b dot
          echo Checkout 2

      - name: Import patches
        run: ./melon import
      
      - name: Build inside Docker
        run: |
          ls -l ./configs/linux
          sudo chmod +x ./configs/linux/build_linux.sh
          ./melon build linux
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: obj-?/dist
