name: Build

on:
  push:
    branches: [ nightly ]
  workflow_dispatch:
  
jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      CI_SKIP_INIT: true
      SHELL: /bin/sh
    steps:
      - uses: actions/checkout@v2

      - name: Disable sscache
        run: |
          sed -i '/ac_add_options --with-ccache=sccache/s/^/#/g' configs/linux/mozconfig
          cat configs/linux/mozconfig

      - name: Set up Git User
        run: |
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git config --global user.name "dothq-robot"

      - name: Install dependencies
        run: |
          npm i typescript

      - name: Download workspace
        run: |
          ./melon download
          cd src
          git init
          echo Init
          git checkout --orphan base
          echo Checkout
          git add -f .
          echo Add
          git commit -am "Firefox"
          echo Commit
          git checkout -b dot
          echo Checkout 2

      - name: Import patches
        run: ./melon import

      - name: Build
        run: |
          cd src
          ./mach bootstrap --application-choice browser --no-interactive
          cd ..
          ./melon build
          cd src
          ./mach package
          cd ..
        
      - name: Upload artifacts
        run: |
          ARTIFACT_NAME="$(find . -name 'dot-*.tar.bz2')"
          AZURE_CONNECTION_STRING="${{ secrets.AZURE_CONNECTION_STRING }}" node upload-artifacts.js linux $ARTIFACT_NAME

      - name: Build success webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: Build
            color: '#2f3136'
            avatarUrl: https://github.com/dothq.png
            description: '**✅ Build on ${{ runner.os }} was successful**'
            text: <@&805943648067780648>
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  windows:
    runs-on: [self-hosted, Windows, X64]
    env:
      CI_SKIP_INIT: true
      SHELL: /bin/sh
    steps:
      - uses: actions/checkout@v2

      - name: Add path
        shell: powershell
        run: |
          echo "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\Administrator\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Disable autocrlf
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          git config core.autocrlf false

      - name: Disable sscache
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          sed -i '/ac_add_options --with-ccache=sccache/s/^/#/g' configs/windows/mozconfig
          echo 'mk_add_options MOZ_MAKE_FLAGS="-j4"' >> configs/windows/mozconfig
          cat configs/windows/mozconfig

      - name: Set up Git
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git config --global user.name "dothq-robot"

      - name: Install Typescript
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          npm i typescript

      - name: Download workspace
        shell: bash -leo pipefail {0}
        run: |
          echo $PWD
          ls
          shopt -s expand_aliases
          xz --version
          ./melon download
          ./melon download-artifacts
          ./windows-init.sh

      - name: Import patches
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          ./melon fix-le
          ./melon import

      - name: Update path
        shell: bash --noprofile --norc -eo pipefail {0}
        run: echo ::set-output name=NPATH::$(echo $PATH)
        id: path

      - name: Build
        shell: cmd
        run: |
          type nul > C:\build-script.sh
          echo PATH="$PATH:${{ steps.path.outputs.NPATH }}:/c/Users/Administrator/.cargo/bin" >> C:\build-script.sh
          echo echo $PATH >> C:\build-script.sh
          echo rustup install stable >> C:\build-script.sh
          echo rustup default stable >> C:\build-script.sh
          echo rustc --version >> C:\build-script.sh
          echo cd /c/_work/browser-ff/browser-ff >> C:\build-script.sh
          echo ./melon build >> C:\build-script.sh
          C:\mozilla-build\start-shell.bat "C:\build-script.sh"
        
      - name: Upload artifacts
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          ARTIFACT_NAME="$(find . -name 'dot-*.exe')"
          AZURE_CONNECTION_STRING="${{ secrets.AZURE_CONNECTION_STRING }}" node upload-artifacts.js windows $ARTIFACT_NAME

      - name: Build success webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: Build
            color: '#2f3136'
            avatarUrl: https://github.com/dothq.png
            description: '**✅ Build on ${{ runner.os }} was successful**'
            text: <@&805943648067780648>
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
