name: Build Dot Browser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Download workspace
        run: ./melon download

      - name: Import patches
        run: ./melon import
      
      - name: Build inside Docker
        run: |
          chmod +x configs/linux/build_linux.sh
          ./melon build linux
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: obj-?/dist
