name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      CI_SKIP_INIT: true
      SHELL: /bin/sh
    steps:
      - uses: actions/checkout@v2

      - name: Disable sscache
        run: |
          sed -i '/ac_add_options --with-ccache=sccache/s/^/#/g' configs/linux/mozconfig
          cat configs/linux/mozconfig

      - name: Set up Git User
        run: |
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git config --global user.name "dothq-robot"

      - name: Install dependencies
        run: |
          npm i typescript

      - name: Download workspace
        run: |
          ./melon download
          cd src
          git init
          echo Init
          git checkout --orphan base
          echo Checkout
          git add -f .
          echo Add
          git commit -am "Firefox"
          echo Commit
          git checkout -b dot
          echo Checkout 2

      - name: Import patches
        run: ./melon import

      - name: Build
        run: |
          cd src
          ./mach bootstrap --application-choice browser --no-interactive
          cd ..
          ./melon build
          cd src
          ./mach package
          cd ..
        
      - name: Upload artifacts
        run: |
          ARTIFACT_NAME="$(find . -name 'dot-*.tar.bz2')"
          AZURE_CONNECTION_STRING="${{ secrets.AZURE_CONNECTION_STRING }}" node upload-artifacts.js linux $ARTIFACT_NAME

      - name: Build success webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: Build
            color: '#2f3136'
            avatarUrl: https://github.com/dothq.png
            description: '**✅ Build on ${{ runner.os }} was successful**'
            text: <@&805943648067780648>
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  windows:
    runs-on: windows-2019
    env:
      CI_SKIP_INIT: true
      SHELL: /bin/sh
    steps:
      - name: Disable autocrlf
        shell: bash
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@v2

      - name: Disable sscache
        shell: bash
        run: |
          sed -i '/ac_add_options --with-ccache=sccache/s/^/#/g' configs/windows/mozconfig
          cat configs/windows/mozconfig

      - name: Set up Git
        shell: bash
        run: |
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git config --global user.name "dothq-robot"

      - name: Clone mozillabuild
        run: |
          curl https://cdn.dothq.co/artifacts/tools/mozilla-build.zip -o mozilla-build.zip
          ls
          7z x mozilla-build.zip -aoa -oC:\mozilla-build 

      - name: Install dependencies
        shell: bash
        run: |
          npm i typescript

      - name: Download workspace
        shell: bash
        run: |
          ./melon download
          ./windows-init.sh

      - name: Import patches
        shell: bash
        run: |
          ./melon fix-le
          ./melon import

      - name: Update path
        shell: bash
        run: echo ::set-output name=NPATH::$(echo $PATH)
        id: path

      - name: Build
        shell: cmd
        run: |
          type nul > C:\script
          echo PATH=$PATH:${{ steps.path.outputs.NPATH }} >> C:\script
          echo echo $PATH >> C:\script
          echo cd /d/a/browser-ff/browser-ff >> C:\script
          echo ./melon build >> C:\script
          echo cd src >> C:\script
          echo ./mach package >> C:\script
          C:\mozilla-build\start-shell.bat "C:\script"
        
      - name: Upload artifacts
        shell: bash
        run: |
          ARTIFACT_NAME="$(find . -name 'dot-*.exe')"
          AZURE_CONNECTION_STRING="${{ secrets.AZURE_CONNECTION_STRING }}" node upload-artifacts.js windows $ARTIFACT_NAME

      - name: Build success webhook
        uses: rjstone/discord-webhook-notify@v1
        with:
            severity: info
            username: Build
            color: '#2f3136'
            avatarUrl: https://github.com/dothq.png
            description: '**✅ Build on ${{ runner.os }} was successful**'
            text: <@&805943648067780648>
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
