name: Enforce code style

on:
  push:
    paths:
      - 'build/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://${{ secrets.ROBOT_TOKEN }}@github.com/dothq/browser-desktop.git
          cd browser-desktop
          git status

      - name: Setup Git
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

      - name: Install dependencies
        run: yarn

      - name: Format
        run: yarn prettier

      - name: Push to GitHub
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git status
          git add .
          git commit -m "🎨 Enforce code style"
          git push origin main