name: Enforce code style

on:
  push:
    paths:
      - 'build/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

      - name: Install dependencies
        run: yarn

      - name: Format
        run: yarn prettier

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v6.2.0
        with:
          message: '🎨 Enforce code style'
          author_name: dothq-robot
          author_email: 72629236+dothq-robot@users.noreply.github.com
          token: ${{ secrets.ROBOT_TOKEN }}
