name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              run: |
                  git clone https://${{ secrets.ROBOT_TOKEN }}@github.com/dothq/browser-desktop.git -b ${GITHUB_REF#refs/heads/}
                  cd browser-desktop
                  git status

            - name: Setup Git
              run: |
                  git config --global user.name "dothq-robot"
                  git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

            - name: Install dependencies
              run: cd browser-desktop && yarn

            - name: Test
              run: cd browser-desktop && yarn test
