name: Update trunk

on:
    push:
      branches:
        nightly
    workflow_dispatch: # manually run

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Install dependencies
              run: |
                npm i typescript
                sudo apt-get update --fix-missing
                sudo apt-get update
                sudo apt-get install dos2unix
        
            - name: Get week number
              id: week
              run: echo "::set-output name=weekno::$(date +%V)"
        
            - name: Cache repository
              uses: actions/cache@v2
              id: cache
              with:
                path: |
                  ./browser-desktop
                key: ${{ jobs.week.outputs.weekno }}
        
            - uses: actions/checkout@v2
              if: steps.cache.outputs.cache-hit != 'true'
              
            - name: Pull in changes
              run: |
                  cd browser-desktop
                  git pull
                  
            - name: Download workspace
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                ./melon download
                cd src
                git init
                echo Init
                git checkout --orphan base
                echo Checkout
                git add -f .
                echo Add
                git commit -am "Firefox"
                echo Commit
                git checkout -b dot
                echo Checkout 2
                cd ..
                sudo rm -rf firefox-*.source.tar.xz
                
            - name: Import patches
              run: |
                cd src
                git checkout .
                cd ..
                ./melon import --minimal
                python3 scripts/patches-applied.py
                
            - name: Push to trunk
              run: |
                git clone https://${{ secrets.ROBOT_TOKEN }}@github.com/dothq/browser-desktop-trunk
                rsync -av --progress src/* trunk --exclude .git
                cd browser-desktop-trunk
                git add .
                git commit -m "🆙 Update trunk (${{ github.sha }}"
                git push
