name: Update trunk

on:
    push:
      branches:
        nightly
    workflow_dispatch: # manually run

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Install dependencies
              run: |
                npm i typescript
                sudo apt-get update --fix-missing
                sudo apt-get update
                sudo apt-get install dos2unix
        
            - name: Set up Git User
              run: |
                git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
                git config --global user.name "dothq-robot"
        
            - uses: actions/checkout@v2
              if: steps.cache.outputs.cache-hit != 'true'
              
            - name: Pull in changes
              run: |
                  cd ~/work/browser-desktop/browser-desktop
                  git pull
                  
            - name: Download workspace
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                ./melon download
                cd src
                git init
                echo Init
                git checkout --orphan base
                echo Checkout
                git add -f . > /dev/null
                echo Add
                git commit -am "Firefox" > /dev/null
                echo Commit
                git checkout -b dot
                echo Checkout 2
                cd ..
                sudo rm -rf firefox-*.source.tar.xz
                
            - name: Import patches
              run: |
                cd src
                git checkout .
                cd ..
                ./melon import --minimal
                python3 scripts/patches-applied.py
                
            - name: Push to trunk
              run: |
                git clone https://${{ secrets.ROBOT_TOKEN }}@github.com/dothq/browser-desktop-trunk
                rsync -av --progress ./src/ ./browser-desktop-trunk --exclude .git
                cd browser-desktop-trunk
                git add .
                git commit -m "🆙 Update trunk (${{ github.sha }})"
                git tag ${{ github.sha }} 
                git push
