name: Update changeset

on:
    push:
    workflow_dispatch: # manually run sync

jobs:
    sync:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Update changeset
              run: |
                  yarn
                  node scripts/ci-update-changeset.js
